app/scanok/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from scanok import excel as scanok_excel
from scanok import views as scanok_views


app_name = 'scanok'

urlpatterns = [
    path('goods/', scanok_views.Goods.as_view(), name='goods'),
    path('goods/create/', scanok_views.good_create, name='good_create'),
    path('goods/update/<int:pk>/', scanok_views.good_update, name='good_update'),
    path('goods/delete/<int:pk>/', scanok_views.good_delete, name='good_delete'),
    path('goods/details/<int:pk>/', scanok_views.GoodsDetails.as_view(), name='good_details'),
    path('goods/search-goods/', csrf_exempt(scanok_views.search_goods), name='search_goods'),

    path('goods/add_barcode/<int:pk>/', scanok_views.barcode_create, name='add_barcode'),
    path('goods/update_barcode/<int:pk>/', scanok_views.barcode_update, name='update_barcode'),
    path('goods/delete_barcode/<int:pk>/', scanok_views.barcode_delete, name='delete_barcode'),
    path('goods/assign_barcode/<int:pk>/', scanok_views.barcode_assign, name='assign_barcode'),

    path('goods/export', scanok_excel.export_goods, name='export_goods'),
    path('goods/settings_xls', scanok_excel.settings_xls, name='settings_xls'),

    path('stores/', scanok_views.Store.as_view(), name='stores'),
    path('stores/create/', scanok_views.store_create, name='store_create'),
    path('stores/delete/<int:pk>/', scanok_views.store_delete, name='store_delete'),
    path('stores/update/<int:pk>/', scanok_views.store_update, name='store_update'),

    path('users/', scanok_views.Users.as_view(), name='users'),
    path('users/create/', scanok_views.user_create, name='user_create'),
    path('users/delete/<int:pk>/', scanok_views.user_delete, name="user_delete"),
    path('users/update/<int:pk>/', scanok_views.user_update, name="user_update"),

    path('dochead/', scanok_views.DocheadTable.as_view(), name='dochead'),
    path('dochead/create/', scanok_views.doc_create, name='doc_create'),
    path('dochead/delete/<int:pk>/', scanok_views.doc_delete, name="dochead_delete"),
    path('dochead/update/<int:pk>/<int:page>/', scanok_views.doc_update, name="dochead_update"),
    path('dochead/update/<int:pk>/<int:page>/search-barcode/', csrf_exempt(scanok_views.search_barcode),
         name='search_barcode'),
    path('dochead/doc_hold/', csrf_exempt(scanok_views.doc_hold), name='doc_hold'),

    path('dochead/update/<int:pk>/<int:page>/add_detail', scanok_views.add_detail, name='add_detail'),
    path('dochead/update/<int:pk>/<int:page>/edit_detail/<int:plug>', scanok_views.update_detail, name='edit_detail'),
    path('dochead/update/<int:pk>/<int:page>/delete_detail/<int:plug>', scanok_views.detail_delete,
         name='detail_delete'),

    path('partners/', scanok_views.Partner.as_view(), name='partners'),
    path('partners/create/', scanok_views.partner_create, name='partner_create'),
    path('partners/delete/<int:pk>/', scanok_views.partner_delete, name="partner_delete"),
    path('partners/update/<int:pk>/', scanok_views.partner_update, name="partner_update"),



]

app/settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('scanok/', include('scanok.urls')),
    path('check-email/', TemplateView.as_view(template_name='activation.html'), name='check-email'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),


    path('__debug__/', include('debug_toolbar.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/scanok/views.py
import json
import uuid
from datetime import datetime

from accounts.models import Device

from django.conf import settings
from django.contrib import messages
from django.core.paginator import EmptyPage, Paginator
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.views.generic import ListView

from django_tables2 import SingleTableView

from scanok.epochtime import data_to_tact
from scanok.forms import BarcodeForm, DocDetailsForm, DocheadForm, GoodForm, PartnerForm, StoreForm, UserForm
from scanok.hashmd5 import str2hash
from scanok.sqlclasstable import Barcode, DocDetails, DocHead, Good, Partners, ScanHistory, Stores, User
from scanok.tables import DocHeadTable
from scanok.util import next_f

from sqlalchemy import create_engine, or_
from sqlalchemy.exc import IntegrityError, NoResultFound
from sqlalchemy.orm import sessionmaker


def conn_db(request):
    current_id = request.user.id
    try:
        database = Device.objects.get(user_id=current_id, current=True).name
    except Device.DoesNotExist:
        raise Http404
    else:
        engine = create_engine(f'mssql+pymssql://{settings.USER}:{settings.PASSWORD}@'
                               f'{settings.SERVER}:{settings.PORT}/{database}', echo=True)

        session = sessionmaker(bind=engine)
        s = session()  # noqa: VNE001
        return s


def good_barcode_list(request, pk=None):
    s = conn_db(request)  # noqa: VNE001
    if pk:
        query = s.query(Good, Barcode).outerjoin(
            Barcode, Barcode.GoodF == Good.GoodF
        ).filter(
            Good.id == pk
        )
    else:
        query = s.query(Good, Barcode).outerjoin(
            Barcode, Barcode.GoodF == Good.GoodF
        ).order_by(-Good.id)

    query_dict = {}
    for key, value in query:
        query_dict.setdefault(key, []).append(value)

    record = list(query_dict.items())

    return record


class Goods(ListView):
    template_name = 'goods.html'
    paginate_by = 25
    context_object_name = 'goods_list'

    def get_queryset(self):
        record = good_barcode_list(self.request)
        return record


class GoodsDetails(ListView):
    template_name = 'good_details.html'
    context_object_name = 'details_list'

    def get_queryset(self):
        record = good_barcode_list(self.request, self.kwargs['pk'])
        return record


def good_update(request, pk):
    record = good_barcode_list(request, pk)

    barcode_list = record[0][1]

    value = record[0][0]

    good_f = value.GoodF
    good_name = value.Name
    good_price = value.Price
    good_unit = value.Unit

    s = conn_db(request)  # noqa: VNE001
    instance = s.query(Good).filter(Good.id == pk)
    if request.method == 'POST':
        form = GoodForm(request.POST)
        if form.is_valid():
            good_name = form.cleaned_data.get('Name')
            good_price = form.cleaned_data.get('Price')
            good_unit = form.cleaned_data['Unit']

            instance.update({
                Good.Name: good_name,
                Good.Price: good_price,
                Good.Unit: good_unit,
                Good.Updated: 1.0,
            })
            s.commit()
            s.close()

            return HttpResponseRedirect('/scanok/goods/')

    else:
        form = GoodForm(initial={'GoodF': good_f, 'Name': good_name, 'Price': good_price, 'Unit': good_unit})

    return render(request, 'good_update.html', context={
        'form': form, 'barcode_list': barcode_list, 'pk': pk
    })


def good_create(request):
    s = conn_db(request)  # noqa: VNE001
    last_good = s.query(Good.GoodF).order_by(-Good.id).first()[0]

    if last_good:
        next_good_f = next_f(last_good)
    else:
        next_good_f = '1'

    if request.method == 'POST':
        form = GoodForm(request.POST)
        if form.is_valid():
            good_f = form.cleaned_data.get('GoodF')
            if not good_f:
                good_f = next_good_f

            name = form.cleaned_data.get('Name')
            price = form.cleaned_data['Price']
            unit = form.cleaned_data['Unit']

            c1 = Good(GoodF=good_f, Name=name, Price=price, Deleted=0, Updated=1, Unit=unit, Field_2='A')
            s.add(c1)
            s.commit()
            pk = c1.id
            s.close()

            return HttpResponseRedirect(f'/scanok/goods/add_barcode/{pk}/')

    else:
        form = GoodForm(initial={'GoodF': next_good_f, 'Unit': 'шт.'})
    return render(request, 'good_create.html', context={'form': form})


def good_delete(request, pk):
    s = conn_db(request)  # noqa: VNE001
    good = s.query(Good).filter(Good.id == pk)

    if request.method == 'POST':
        good.update({Good.Deleted: 1})
        s.query(Barcode).filter(Barcode.GoodF == good[0].GoodF).update({Barcode.Deleted: 1})
        s.commit()

        s.close()
        return HttpResponseRedirect('/scanok/goods/')
    else:
        return render(request, 'good_delete.html', context={'good': good})


def search_goods(request):
    if request.method == 'POST':
        search = json.loads(request.body).get('searchText')

        s = conn_db(request)  # noqa: VNE001
        goods = s.query(Good, Barcode).join(
            Barcode, Barcode.GoodF == Good.GoodF
        ).filter(or_(Barcode.BarcodeName == search, Good.GoodF == search, Good.Name.contains(search)))

        query_dict = {}

        for key, value in goods:
            value.__dict__.pop('_sa_instance_state')
            if query_dict.get(key):
                query_dict[key].append(value.__dict__)
            else:
                query_dict.update({key: [value.__dict__]})

        data = []
        for key, value in query_dict.items():
            key.__dict__.pop('_sa_instance_state')
            record = key.__dict__
            record.update({'Barcode': value})
            data.append(record)

        return JsonResponse(data, safe=False)


def barcode_create(request, pk):
    s = conn_db(request)  # noqa: VNE001

    good = s.query(Good).filter(Good.id == pk).one()
    good_f = good.GoodF
    if request.method == 'POST':
        form = BarcodeForm(request.POST)
        if form.is_valid():
            barcode = form.cleaned_data.get('BarcodeName')
            code = form.cleaned_data['Code']
            count = form.cleaned_data['Count']

            try:
                c1 = Barcode(GoodF=good_f, BarcodeName=barcode, Code=code, Deleted=0, Updated=1, Count=count)
                if c1:
                    s.add(c1)
                    s.commit()
                    s.close()
            except IntegrityError:
                request.session['entered_barcode'] = barcode
                request.session['entered_code'] = code
                request.session['entered_count'] = count
                request.session['good_f'] = good_f
                return HttpResponseRedirect(f'/scanok/goods/add_barcode/{pk}/#error')

            return HttpResponseRedirect(f'/scanok/goods/update/{pk}/')

    else:
        form = BarcodeForm(initial={'GoodF': good_f.zfill(6), 'Code': good_f.zfill(6), 'Count': 1.0})
    return render(request, 'barcode_create.html', context={'form': form, 'Good': good})


def barcode_update(request, pk):
    s = conn_db(request)  # noqa: VNE001

    query = s.query(Good.id, Barcode.GoodF, Barcode.BarcodeName, Barcode.Code, Barcode.Count).join(
        Barcode, Barcode.GoodF == Good.GoodF
    ).filter(
        Barcode.id == pk
    ).one()

    good_f = query['GoodF']
    barcode_name = query['BarcodeName']
    code = query['Code']
    count = query['Count']
    good_id = query['id']

    if request.method == 'POST':
        form = BarcodeForm(request.POST)
        if form.is_valid():
            barcode_name = form.cleaned_data.get('BarcodeName')
            code = form.cleaned_data['Code']
            count = form.cleaned_data['Count']

            instance = s.query(Barcode).filter(Barcode.id == pk)

            instance.update({
                Barcode.Code: code,
                Barcode.Count: count,
                Barcode.Updated: 1.0,
            })
            s.commit()
            s.close()
            return HttpResponseRedirect(f'/scanok/goods/update/{good_id}/')

    form = BarcodeForm(initial={
        'GoodF': good_f.zfill(6),
        'BarcodeName': barcode_name,
        'Code': code.zfill(6),
        'Count': count,
    })

    return render(request, 'barcode_update.html', context={'form': form})


def barcode_delete(request, pk):
    s = conn_db(request)  # noqa: VNE001

    instance = s.query(Good.id, Barcode.BarcodeName).join(
        Barcode, Barcode.GoodF == Good.GoodF
    ).filter(
        Barcode.id == pk
    ).one()

    barcode_name = instance['BarcodeName']
    good_id = instance['id']

    if request.method == 'POST':
        s.query(Barcode).filter(Barcode.id == pk).update({Barcode.Deleted: 1})
        s.commit()
        return HttpResponseRedirect(f'/scanok/goods/update/{good_id}/')

    return render(request, 'barcode_delete.html', context={'BarcodeName': barcode_name})


def barcode_assign(request, pk):
    barcode = request.session.get('entered_barcode')
    code = request.session.get('entered_code')
    count = request.session.get('entered_count')
    good_f = request.session.get('good_f')

    s = conn_db(request)  # noqa: VNE001

    instance = s.query(Barcode).filter(Barcode.BarcodeName == barcode)

    instance.update({
        Barcode.GoodF: good_f,
        Barcode.Code: code,
        Barcode.Count: count,
        Barcode.Updated: 1.0,
        Barcode.Deleted: 0.0,
    })
    s.commit()
    s.close()

    del request.session['entered_barcode']
    del request.session['entered_code']
    del request.session['entered_count']
    del request.session['good_f']

    return HttpResponseRedirect(f'/scanok/goods/update/{pk}/')


class Store(ListView):
    template_name = 'stores.html'
    context_object_name = 'stores_list'

    def get_queryset(self):

app/scanok/templates/detail_delete.html
{% extends 'base.html' %}
{% block title %}Delete{% endblock %}
{% block content %}
{% for i in detail %}
<p> Do you want to delete {{ i.DocDetailsF }} from Document? </p>
{% endfor %}
<form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>



{% endblock content %}

app/scanok/templates/doc_hold.html
{% if record.DocStatus >= 0 %}

<input type="checkbox" name="hold" checked disabled>

{% else %}

<input type="checkbox" name="hold" value={{record.id}} onclick="cl()">

{% endif %}

app/scanok/templates/doc_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Update{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {% crispy form %}
</form>

<hr size="3" color=black>

<div>
    {% if docstatus < 0 %}
        <table style="width: 100%">
            <tr>
                <td>
                    <div>
                        <p>
                        <form action="{% url 'scanok:add_detail' pk page%}">
                            <button class="btn btn-secondary">Add Details</button>
                        </form>
                        </p>
                    </div>
                </td>
                <td align="right">
                    <div class="col-md-8">
                        <div class="form-group">
                            <input type="text" class="form-control" id="Barcode" placeholder="Barcode" autofocus>
                        </div>
                    </div>
                </td>
            </tr>
        </table>
    {% endif %}


    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col">GoodF</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Count_Doc</th>
            <th scope="col">Count_Real</th>
            {% if docstatus < 0 %}
            <th scope="col"></th>
            {% endif %}
        </tr>

        </thead>

        {% for row in doc_details %}

        <tr class="clickable" data-toggle="collapse" data-target="#{{ row.0.0 }}">
            <td>{{ row.0.1 }}</td>
            <td>{{ row.0.2 }}</td>
            <td align="right">{{ row.0.3|floatformat:2 }}</td>
            <td align="center">{{ row.0.4 }}</td>
            <td align="center">{{ row.0.5 }}</td>
            {% if docstatus < 0 %}
            <td>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2"
                            data-bs-toggle="dropdown" aria-expanded="false"></button>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                        <li><a class="dropdown-item" href="{% url 'scanok:edit_detail' pk page row.0.0%}">Edit</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'scanok:detail_delete' pk page row.0.0%}">Delete</a>
                        </li>
                    </ul>
                </div>
            </td>
            {% endif %}
        </tr>

        <tbody id="{{ row.0.0 }}" class="collapse">
        <tr class="box">
            <td colspan="6" style="padding:0">
                <table class="table table-striped table-dark">
                    <thead>
                    <tr>
                        <th>Code</th>
                        <th>BarcodeName</th>
                        <th>Count</th>
                        <th>Date</th>
                        <th>Comment</th>
                    </tr>
                    </thead>
                    {% for scan_history in row.1 %}

                    <tr>
                        <td>{{ scan_history.GoodF}}</td>
                        <td>{{ scan_history.BarcodeName }}</td>
                        <td>{{ scan_history.Count }}</td>
                        <td>{{ scan_history.lastChanged }}</td>
                        <td>{% if scan_history.Comment %}
                            {{ scan_history.Comment }}
                            {% endif %}
                        </td>
                    </tr>

                    {% endfor %}


                </table>

            </td>
        </tr>
        </tbody>
        {% endfor %}
    </table>
</div>

<!-- Pagination -->

<nav>
    <ul class="pagination justify-content-center">
        <li class="page-item {% if not doc_details.has_previous %} disabled {% endif %}">
            <a class="page-link"
               href="{% if doc_details.has_previous %} {% url 'scanok:dochead_update' pk doc_details.previous_page_number %}{% endif %} ">&laquo;</a>
        </li>

        {% if doc_details.number|add:'-1' > 1 %}
        <li class="page-item disabled"><a class="page-link">&hellip;</a></li>
        {% endif %}

        {% for i in doc_details.paginator.page_range %}
        {% if doc_details.number == i %}
        <li class="active page-item disabled"><a class="page-link" href="#">{{ i }}</a></li>
        {% elif i > doc_details.number|add:'-2' and i < doc_details.number|add:'2' %}
        <li class="page-item"><a class="page-link" href="{% url 'scanok:dochead_update' pk i %}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}

        {% if users.paginator.num_pages > users.number|add:'1' %}
        <li class="page-item disabled"><a class="page-link" href="#">&hellip;</a></li>
        {% endif %}

        <li class="page-item {% if not doc_details.has_next %} disabled {% endif %}">
            <a class="page-link"
               href="{% if doc_details.has_next %} {% url 'scanok:dochead_update' pk doc_details.next_page_number %} {% endif %}">&raquo;</a>
        </li>
    </ul>
</nav>
<!-- END Pagination -->
<div id="error" class="modalbackground">
    <div class="modalwindow">
        <h3>Error!</h3>
        <p>Barcode not found</p>
        <p></p>

        <a href=" ">Cancel</a>

    </div>
</div>

<script src="{% static 'js/searchBarcode.js' %}"></script>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>


{% endblock content %}

app/scanok/templates/dochead_action.html
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2"
            data-bs-toggle="dropdown" aria-expanded="false"></button>
    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
        {% if record.DocStatus < 0 %}
        <li><a class="dropdown-item" href="{% url 'scanok:dochead_update' record.id 1%}">Edit</a></li>
        <li><a class="dropdown-item" href="{% url 'scanok:dochead_delete' record.id%}">Delete</a>
        {% else %}
        <li><a class="dropdown-item" href="{% url 'scanok:dochead_update' record.id 1%}">View</a></li>
        {% endif %}
        </li>
    </ul>
</div>

app/scanok/templates/dochead_delete.html
{% extends 'base.html' %}
{% block title %}Delete{% endblock %}
{% block content %}
{% for i in dochead %}
<p> Do you want to delete Document {{ i.Comment }}? </p>
{% endfor %}
<form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>



{% endblock content %}

app/scanok/templates/good_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load extra_teg %}
{% block title %}Good Update{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-6 mb-0">
            {{ form.GoodF|attr:"disabled=True"|as_crispy_field }}

            {{ form.Name|as_crispy_field }}

            {{ form.Price|as_crispy_field }}

            {{ form.Unit|as_crispy_field }}
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Update</button>
</form>

<hr size="3", color=black>

<div>
    <div>
        <p>
        <form action="{% url 'scanok:add_barcode' pk %}">
            <button class="btn btn-secondary">Add Barcode</button>
        </form>
        </p>
    </div>
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col">GoodF</th>
            <th scope="col">Code</th>
            <th scope="col">BarcodeName</th>
            <th scope="col">Count</th>
            <th scope="col"></th>
        </tr>
        </thead>

        {% for barcode in barcode_list %}
        {% if barcode.Deleted == False %}
        <tr>
            <td>{{ barcode.GoodF|zfill:6 }}</td>
            <td>{{ barcode.Code }}</td>
            <td>{{ barcode.BarcodeName }}</td>
            <td>{{ barcode.Count }}</td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2"
                            data-bs-toggle="dropdown" aria-expanded="false"></button>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                        <li><a class="dropdown-item" href="{% url 'scanok:update_barcode' barcode.id %}">Edit</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'scanok:delete_barcode' barcode.id %}">Delete</a>
                        </li>
                    </ul>
                </div>
            </td>
        </tr>
        {% endif %}
        {% endfor %}
    </table>
</div>

{% endblock content %}

app/scanok/templates/partner_delete.html
{% extends 'base.html' %}
{% block title %}Delete{% endblock %}
{% block content %}
{% for i in partner %}
<p> Do you want to delete Partner {{ i.NamePartner }}? </p>
{% endfor %}
<form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>



{% endblock content %}

app/scanok/templates/settings_xls.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Setting import export{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {% crispy form %}
</form>


{% endblock content %}

app/scanok/templates/store_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Store create{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Create</button>
</form>



{% endblock content %}

app/scanok/templates/store_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block title %}Partner Update{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-6 mb-0">
        {{ form.StoreF|attr:"disabled=True"|as_crispy_field }}

        {{ form.NameStore|as_crispy_field }}
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Update</button>
</form>


{% endblock content %}

app/scanok/templates/stores.html
{% extends 'base.html' %}
{% block title %}Stores{% endblock %}

{% block content %}
{% include 'includes/select_device.html' %}
<div class="row">
    <div class="col">
        <div>
            <p>
            <form action="{% url 'scanok:store_create' %}">
                <button class="btn btn-secondary">Create</button>
            </form>
            </p>
        </div>
        <table class="table table-striped table-hover">
            <tr>
                <th scope="col">StoreF</th>
                <th scope="col">NameStore</th>
                <th scope="col">Actions</th>
            </tr>
            {% for row in stores_list %}
            {% if row.Deleted == False %}
            <tr>
                <td width="50" align="left">{{row.StoreF}}</td>
                <td align="left">{{row.NameStore}}</td>
                <td width="10" align="center">
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2"
                                data-bs-toggle="dropdown" aria-expanded="false"></button>
                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                            <li><a class="dropdown-item" href="{% url 'scanok:store_update' row.id %}">Edit</a></li>
                            <li><a class="dropdown-item" href="{% url 'scanok:store_delete' row.id %}">Delete</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
            {% endif %}
            {% endfor %}

        </table>
    </div>
</div>

{% include 'includes/pagination.html' %}

{% endblock content %}

app/scanok/templates/user_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}User create{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Create</button>
</form>



{% endblock content %}

app/scanok/templates/user_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block title %}User Update{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-6 mb-0">

        {{ form.UserF|attr:"disabled=True"|as_crispy_field }}
        {{ form.Login|as_crispy_field }}
        {{ form.Name|as_crispy_field }}
        {{ form.Password|as_crispy_field }}

        </div>
    </div>

    <button type="submit" class="btn btn-primary">Update</button>
</form>


{% endblock content %}

app/scanok/templates/users.html
{% extends 'base.html' %}
{% block title %}Users{% endblock %}

{% block content %}
{% include 'includes/select_device.html' %}


<div class="row">
    <div class="col">
        <div>
            <p>
            <form action="{% url 'scanok:user_create' %}">
                <button class="btn btn-secondary">Create</button>
            </form>
            </p>
        </div>

        <table class="table table-striped table-hover">
            <tr>
                <th scope="col">UserF</th>
                <th scope="col">Name</th>
                <th scope="col">Login</th>

                <th scope="col"></th>
            </tr>
            {% for row in users_list %}
            {% if row.UserF == -1 %}
            <!-- continue -->
            {% else %}
            {% if row.Deleted == False %}
            <tr>
                <td>{{row.UserF}}</td>
                <td>{{row.Name}}</td>
                <td>{{row.Login}}</td>

                <td width="10" align="center">
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2"
                                data-bs-toggle="dropdown" aria-expanded="false"></button>
                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                            <li><a class="dropdown-item" href="{% url 'scanok:user_update' row.id %}">Edit</a></li>
                            <li><a class="dropdown-item" href="{% url 'scanok:user_delete' row.id %}">Delete</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
            {% endif %}
            {% endif %}
            {% endfor %}

        </table>
    </div>
</div>
{% include 'includes/pagination.html' %}
{% endblock content %}