app/accounts/urls.py
from accounts import views

from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.decorators.csrf import csrf_exempt


app_name = 'accounts'

urlpatterns = [
    path('my-profile/', views.MyProfile.as_view(), name='my-profile'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('activate/<uuid:username>/', views.ActivateUser.as_view(), name='activate-user'),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('devices/', views.Devices.as_view(), name='devices'),
    path('devices/create/', views.DeviceCreate.as_view(), name='device_create'),
    path('devices/update/<int:pk>/', views.DeviceUpdate.as_view(), name='device_update'),
    path('devices/delete/<int:pk>/', views.DeviceDelete.as_view(), name='device_delete'),
    path('devices/search-devices/', csrf_exempt(views.search_devices), name='search_devices'),
    path('devices/current-device/', csrf_exempt(views.current_device), name='current_devices'),
    path('devices/list-devices/', csrf_exempt(views.list_devices), name='list_devices'),


]

app/scanok/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from scanok import excel as scanok_excel
from scanok import views as scanok_views


app_name = 'scanok'

urlpatterns = [
    path('goods/', scanok_views.Goods.as_view(), name='goods'),
    path('goods/create/', scanok_views.good_create, name='good_create'),
    path('goods/update/<int:pk>/', scanok_views.good_update, name='good_update'),
    path('goods/delete/<int:pk>/', scanok_views.good_delete, name='good_delete'),
    path('goods/details/<int:pk>/', scanok_views.GoodsDetails.as_view(), name='good_details'),
    path('goods/search-goods/', csrf_exempt(scanok_views.search_goods), name='search_goods'),

    path('goods/add_barcode/<int:pk>/', scanok_views.barcode_create, name='add_barcode'),
    path('goods/update_barcode/<int:pk>/', scanok_views.barcode_update, name='update_barcode'),
    path('goods/delete_barcode/<int:pk>/', scanok_views.barcode_delete, name='delete_barcode'),
    path('goods/assign_barcode/<int:pk>/', scanok_views.barcode_assign, name='assign_barcode'),

    path('goods/export', scanok_excel.export_goods, name='export_goods'),
    path('goods/settings_xls', scanok_excel.settings_xls, name='settings_xls'),

    path('stores/', scanok_views.Store.as_view(), name='stores'),
    path('stores/create/', scanok_views.store_create, name='store_create'),
    path('stores/delete/<int:pk>/', scanok_views.store_delete, name='store_delete'),
    path('stores/update/<int:pk>/', scanok_views.store_update, name='store_update'),

    path('users/', scanok_views.Users.as_view(), name='users'),
    path('users/create/', scanok_views.user_create, name='user_create'),
    path('users/delete/<int:pk>/', scanok_views.user_delete, name="user_delete"),
    path('users/update/<int:pk>/', scanok_views.user_update, name="user_update"),

    path('dochead/', scanok_views.DocheadTable.as_view(), name='dochead'),
    path('dochead/create/', scanok_views.doc_create, name='doc_create'),
    path('dochead/delete/<int:pk>/', scanok_views.doc_delete, name="dochead_delete"),
    path('dochead/update/<int:pk>/<int:page>/', scanok_views.doc_update, name="dochead_update"),
    path('dochead/update/<int:pk>/<int:page>/search-barcode/', csrf_exempt(scanok_views.search_barcode),
         name='search_barcode'),
    path('dochead/doc_hold/', csrf_exempt(scanok_views.doc_hold), name='doc_hold'),

    path('dochead/update/<int:pk>/<int:page>/add_detail', scanok_views.add_detail, name='add_detail'),
    path('dochead/update/<int:pk>/<int:page>/edit_detail/<int:plug>', scanok_views.update_detail, name='edit_detail'),
    path('dochead/update/<int:pk>/<int:page>/delete_detail/<int:plug>', scanok_views.detail_delete,
         name='detail_delete'),

    path('partners/', scanok_views.Partner.as_view(), name='partners'),
    path('partners/create/', scanok_views.partner_create, name='partner_create'),
    path('partners/delete/<int:pk>/', scanok_views.partner_delete, name="partner_delete"),
    path('partners/update/<int:pk>/', scanok_views.partner_update, name="partner_update"),



]

app/settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('scanok/', include('scanok.urls')),
    path('check-email/', TemplateView.as_view(template_name='activation.html'), name='check-email'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),


    path('__debug__/', include('debug_toolbar.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/templates/device_action.html
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2"
            data-bs-toggle="dropdown" aria-expanded="false"></button>
    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
        <li><a class="dropdown-item active"
               href="#">Detail</a></li>
        <li><a class="dropdown-item" href="{% url 'accounts:device_update' record.id %}">Edit</a></li>
        <li><a class="dropdown-item" href="{% url 'accounts:device_delete'  record.id %}">Delete</a>
        </li>
    </ul>
</div>

app/templates/device_create.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}Add Device{% endblock %}


<div class="">
    {% block content %}


    <p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
    <form action="" method="post">{% csrf_token %}
        <table>
            {{ wizard.management_form }}
            {% if wizard.form.forms %}
            {{ wizard.form.management_form|crispy }}
            {% for form in wizard.form.forms %}
            {{ form|crispy }}
            {% endfor %}
            {% else %}
            {{ wizard.form|crispy }}
            {% endif %}
        </table>

        <input type="submit" value="submit"/>
    </form>

    {% endblock content %}
</div>

app/templates/device_current.html
{% if record.current == True %}

<input type="radio" name="current" value={{record.id}} onclick="cl()" checked>

{% else %}

<input type="radio" name="current" value={{record.id}} onclick="cl()">

{% endif %}

app/templates/device_delete.html
{% extends 'base.html' %}
{% block title %}Device Update{% endblock %}
{% block content %}

<p>Do you want to delete {{ device.name }}'</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>



{% endblock content %}

app/templates/device_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block title %}Device Update{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-6 mb-0">
        {{ form.name|as_crispy_field }}

        {{ form.pseudonym|as_crispy_field }}

        {{ form.current|as_crispy_field }}
        </div>
    </div>

    <button type="submit">Update</button>
</form>



{% endblock content %}

app/templates/devices.html
{% extends 'base.html' %}
{% load static %}
{% load render_table from django_tables2 %}
{% block title %}Devices{% endblock %}

{% block content %}

<div class="row">
    <div class="col">
        {% if request.user.is_superuser %}
        <div>
            <p>
            <form action="{% url 'accounts:device_create' %}">
                <button class="btn btn-secondary">Add Device</button>
            </form>
            </p>
        </div>
        {% else %}
        <div>
            <p>
            </p>
        </div>
        {% endif %}
        <div class="row">
            <div class="col-md-8"></div>
            <div class="col-md-8">
                <div class="form-group">
                    <input type="text" class="form-control" id="searchField" placeholder="Search">
                </div>
            </div>

        </div>

        <div class="app-table">
            {% render_table table %}
        </div>

        <div class="table-output">

            <table class="table">
                <thead>
                <tr>
                    <th class="orderable">Name</th>
                    <th class="orderable">Pseudonym</th>
                    <th class="orderable">Created</th>
                    <th class="orderable"></th>
                    <th></th>
                </tr>
                </thead>

                <tbody class="table-body">

                </tbody>
            </table>

        </div>
    </div>

</div>


<script src="{% static 'js/searchDevices.js' %}"></script>
<script src="{% static 'js/radioDevices.js' %}"></script>

{% endblock content %}

app/templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}

<h1>Home</h1>
<div>
    Welcome to Scanok
</div>

{% endblock content %}