app/accounts/urls.py
from accounts import views

from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.decorators.csrf import csrf_exempt


app_name = 'accounts'

urlpatterns = [
    path('my-profile/', views.MyProfile.as_view(), name='my-profile'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('activate/<uuid:username>/', views.ActivateUser.as_view(), name='activate-user'),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('devices/', views.Devices.as_view(), name='devices'),
    path('devices/create/', views.DeviceCreate.as_view(), name='device_create'),
    path('devices/update/<int:pk>/', views.DeviceUpdate.as_view(), name='device_update'),
    path('devices/delete/<int:pk>/', views.DeviceDelete.as_view(), name='device_delete'),
    path('devices/search-devices/', csrf_exempt(views.search_devices), name='search_devices'),
    path('devices/current-device/', csrf_exempt(views.current_device), name='current_devices'),
    path('devices/list-devices/', csrf_exempt(views.list_devices), name='list_devices'),


]

app/scanok/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from scanok import excel as scanok_excel
from scanok import views as scanok_views


app_name = 'scanok'

urlpatterns = [
    path('goods/', scanok_views.Goods.as_view(), name='goods'),
    path('goods/create/', scanok_views.good_create, name='good_create'),
    path('goods/update/<int:pk>/', scanok_views.good_update, name='good_update'),
    path('goods/delete/<int:pk>/', scanok_views.good_delete, name='good_delete'),
    path('goods/details/<int:pk>/', scanok_views.GoodsDetails.as_view(), name='good_details'),
    path('goods/search-goods/', csrf_exempt(scanok_views.search_goods), name='search_goods'),

    path('goods/add_barcode/<int:pk>/', scanok_views.barcode_create, name='add_barcode'),
    path('goods/update_barcode/<int:pk>/', scanok_views.barcode_update, name='update_barcode'),
    path('goods/delete_barcode/<int:pk>/', scanok_views.barcode_delete, name='delete_barcode'),
    path('goods/assign_barcode/<int:pk>/', scanok_views.barcode_assign, name='assign_barcode'),

    path('goods/export', scanok_excel.export_goods, name='export_goods'),
    path('goods/settings_xls', scanok_excel.settings_xls, name='settings_xls'),

    path('stores/', scanok_views.Store.as_view(), name='stores'),
    path('stores/create/', scanok_views.store_create, name='store_create'),
    path('stores/delete/<int:pk>/', scanok_views.store_delete, name='store_delete'),
    path('stores/update/<int:pk>/', scanok_views.store_update, name='store_update'),

    path('users/', scanok_views.Users.as_view(), name='users'),
    path('users/create/', scanok_views.user_create, name='user_create'),
    path('users/delete/<int:pk>/', scanok_views.user_delete, name="user_delete"),
    path('users/update/<int:pk>/', scanok_views.user_update, name="user_update"),

    path('dochead/', scanok_views.DocheadTable.as_view(), name='dochead'),
    path('dochead/create/', scanok_views.doc_create, name='doc_create'),
    path('dochead/delete/<int:pk>/', scanok_views.doc_delete, name="dochead_delete"),
    path('dochead/update/<int:pk>/<int:page>/', scanok_views.doc_update, name="dochead_update"),
    path('dochead/update/<int:pk>/<int:page>/search-barcode/', csrf_exempt(scanok_views.search_barcode),
         name='search_barcode'),
    path('dochead/doc_hold/', csrf_exempt(scanok_views.doc_hold), name='doc_hold'),

    path('dochead/update/<int:pk>/<int:page>/add_detail', scanok_views.add_detail, name='add_detail'),
    path('dochead/update/<int:pk>/<int:page>/edit_detail/<int:plug>', scanok_views.update_detail, name='edit_detail'),
    path('dochead/update/<int:pk>/<int:page>/delete_detail/<int:plug>', scanok_views.detail_delete,
         name='detail_delete'),

    path('partners/', scanok_views.Partner.as_view(), name='partners'),
    path('partners/create/', scanok_views.partner_create, name='partner_create'),
    path('partners/delete/<int:pk>/', scanok_views.partner_delete, name="partner_delete"),
    path('partners/update/<int:pk>/', scanok_views.partner_update, name="partner_update"),



]

app/settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('scanok/', include('scanok.urls')),
    path('check-email/', TemplateView.as_view(template_name='activation.html'), name='check-email'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),


    path('__debug__/', include('debug_toolbar.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/scanok/views.py
import json
import uuid
from datetime import datetime

from accounts.models import Device

from django.conf import settings
from django.contrib import messages
from django.core.paginator import EmptyPage, Paginator
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.views.generic import ListView

from django_tables2 import SingleTableView

from scanok.epochtime import data_to_tact
from scanok.forms import BarcodeForm, DocDetailsForm, DocheadForm, GoodForm, PartnerForm, StoreForm, UserForm
from scanok.hashmd5 import str2hash
from scanok.sqlclasstable import Barcode, DocDetails, DocHead, Good, Partners, ScanHistory, Stores, User
from scanok.tables import DocHeadTable
from scanok.util import next_f

from sqlalchemy import create_engine, or_
from sqlalchemy.exc import IntegrityError, NoResultFound
from sqlalchemy.orm import sessionmaker


def conn_db(request):
    current_id = request.user.id
    try:
        database = Device.objects.get(user_id=current_id, current=True).name
    except Device.DoesNotExist:
        raise Http404
    else:
        engine = create_engine(f'mssql+pymssql://{settings.USER}:{settings.PASSWORD}@'
                               f'{settings.SERVER}:{settings.PORT}/{database}', echo=True)

        session = sessionmaker(bind=engine)
        s = session()  # noqa: VNE001
        return s


def good_barcode_list(request, pk=None):
    s = conn_db(request)  # noqa: VNE001
    if pk:
        query = s.query(Good, Barcode).outerjoin(
            Barcode, Barcode.GoodF == Good.GoodF
        ).filter(
            Good.id == pk
        )
    else:
        query = s.query(Good, Barcode).outerjoin(
            Barcode, Barcode.GoodF == Good.GoodF
        ).order_by(-Good.id)

    query_dict = {}
    for key, value in query:
        query_dict.setdefault(key, []).append(value)

    record = list(query_dict.items())

    return record


class Goods(ListView):
    template_name = 'goods.html'
    paginate_by = 25
    context_object_name = 'goods_list'

    def get_queryset(self):
        record = good_barcode_list(self.request)
        return record


class GoodsDetails(ListView):
    template_name = 'good_details.html'
    context_object_name = 'details_list'

    def get_queryset(self):
        record = good_barcode_list(self.request, self.kwargs['pk'])
        return record


def good_update(request, pk):
    record = good_barcode_list(request, pk)

    barcode_list = record[0][1]

    value = record[0][0]

    good_f = value.GoodF
    good_name = value.Name
    good_price = value.Price
    good_unit = value.Unit

    s = conn_db(request)  # noqa: VNE001
    instance = s.query(Good).filter(Good.id == pk)
    if request.method == 'POST':
        form = GoodForm(request.POST)
        if form.is_valid():
            good_name = form.cleaned_data.get('Name')
            good_price = form.cleaned_data.get('Price')
            good_unit = form.cleaned_data['Unit']

            instance.update({
                Good.Name: good_name,
                Good.Price: good_price,
                Good.Unit: good_unit,
                Good.Updated: 1.0,
            })
            s.commit()
            s.close()

            return HttpResponseRedirect('/scanok/goods/')

    else:
        form = GoodForm(initial={'GoodF': good_f, 'Name': good_name, 'Price': good_price, 'Unit': good_unit})

    return render(request, 'good_update.html', context={
        'form': form, 'barcode_list': barcode_list, 'pk': pk
    })


def good_create(request):
    s = conn_db(request)  # noqa: VNE001
    last_good = s.query(Good.GoodF).order_by(-Good.id).first()[0]

    if last_good:
        next_good_f = next_f(last_good)
    else:
        next_good_f = '1'

    if request.method == 'POST':
        form = GoodForm(request.POST)
        if form.is_valid():
            good_f = form.cleaned_data.get('GoodF')
            if not good_f:
                good_f = next_good_f

            name = form.cleaned_data.get('Name')
            price = form.cleaned_data['Price']
            unit = form.cleaned_data['Unit']

            c1 = Good(GoodF=good_f, Name=name, Price=price, Deleted=0, Updated=1, Unit=unit, Field_2='A')
            s.add(c1)
            s.commit()
            pk = c1.id
            s.close()

            return HttpResponseRedirect(f'/scanok/goods/add_barcode/{pk}/')

    else:
        form = GoodForm(initial={'GoodF': next_good_f, 'Unit': 'шт.'})
    return render(request, 'good_create.html', context={'form': form})


def good_delete(request, pk):
    s = conn_db(request)  # noqa: VNE001
    good = s.query(Good).filter(Good.id == pk)

    if request.method == 'POST':
        good.update({Good.Deleted: 1})
        s.query(Barcode).filter(Barcode.GoodF == good[0].GoodF).update({Barcode.Deleted: 1})
        s.commit()

        s.close()
        return HttpResponseRedirect('/scanok/goods/')
    else:
        return render(request, 'good_delete.html', context={'good': good})


def search_goods(request):
    if request.method == 'POST':
        search = json.loads(request.body).get('searchText')

        s = conn_db(request)  # noqa: VNE001
        goods = s.query(Good, Barcode).join(
            Barcode, Barcode.GoodF == Good.GoodF
        ).filter(or_(Barcode.BarcodeName == search, Good.GoodF == search, Good.Name.contains(search)))

        query_dict = {}

        for key, value in goods:
            value.__dict__.pop('_sa_instance_state')
            if query_dict.get(key):
                query_dict[key].append(value.__dict__)
            else:
                query_dict.update({key: [value.__dict__]})

        data = []
        for key, value in query_dict.items():
            key.__dict__.pop('_sa_instance_state')
            record = key.__dict__
            record.update({'Barcode': value})
            data.append(record)

        return JsonResponse(data, safe=False)


def barcode_create(request, pk):
    s = conn_db(request)  # noqa: VNE001

    good = s.query(Good).filter(Good.id == pk).one()
    good_f = good.GoodF
    if request.method == 'POST':
        form = BarcodeForm(request.POST)
        if form.is_valid():
            barcode = form.cleaned_data.get('BarcodeName')
            code = form.cleaned_data['Code']
            count = form.cleaned_data['Count']

            try:
                c1 = Barcode(GoodF=good_f, BarcodeName=barcode, Code=code, Deleted=0, Updated=1, Count=count)
                if c1:
                    s.add(c1)
                    s.commit()
                    s.close()
            except IntegrityError:
                request.session['entered_barcode'] = barcode
                request.session['entered_code'] = code
                request.session['entered_count'] = count
                request.session['good_f'] = good_f
                return HttpResponseRedirect(f'/scanok/goods/add_barcode/{pk}/#error')

            return HttpResponseRedirect(f'/scanok/goods/update/{pk}/')

    else:
        form = BarcodeForm(initial={'GoodF': good_f.zfill(6), 'Code': good_f.zfill(6), 'Count': 1.0})
    return render(request, 'barcode_create.html', context={'form': form, 'Good': good})


def barcode_update(request, pk):
    s = conn_db(request)  # noqa: VNE001

    query = s.query(Good.id, Barcode.GoodF, Barcode.BarcodeName, Barcode.Code, Barcode.Count).join(
        Barcode, Barcode.GoodF == Good.GoodF
    ).filter(
        Barcode.id == pk
    ).one()

    good_f = query['GoodF']
    barcode_name = query['BarcodeName']
    code = query['Code']
    count = query['Count']
    good_id = query['id']

    if request.method == 'POST':
        form = BarcodeForm(request.POST)
        if form.is_valid():
            barcode_name = form.cleaned_data.get('BarcodeName')
            code = form.cleaned_data['Code']
            count = form.cleaned_data['Count']

            instance = s.query(Barcode).filter(Barcode.id == pk)

            instance.update({
                Barcode.Code: code,
                Barcode.Count: count,
                Barcode.Updated: 1.0,
            })
            s.commit()
            s.close()
            return HttpResponseRedirect(f'/scanok/goods/update/{good_id}/')

    form = BarcodeForm(initial={
        'GoodF': good_f.zfill(6),
        'BarcodeName': barcode_name,
        'Code': code.zfill(6),
        'Count': count,
    })

    return render(request, 'barcode_update.html', context={'form': form})


def barcode_delete(request, pk):
    s = conn_db(request)  # noqa: VNE001

    instance = s.query(Good.id, Barcode.BarcodeName).join(
        Barcode, Barcode.GoodF == Good.GoodF
    ).filter(
        Barcode.id == pk
    ).one()

    barcode_name = instance['BarcodeName']
    good_id = instance['id']

    if request.method == 'POST':
        s.query(Barcode).filter(Barcode.id == pk).update({Barcode.Deleted: 1})
        s.commit()
        return HttpResponseRedirect(f'/scanok/goods/update/{good_id}/')

    return render(request, 'barcode_delete.html', context={'BarcodeName': barcode_name})


def barcode_assign(request, pk):
    barcode = request.session.get('entered_barcode')
    code = request.session.get('entered_code')
    count = request.session.get('entered_count')
    good_f = request.session.get('good_f')

    s = conn_db(request)  # noqa: VNE001

    instance = s.query(Barcode).filter(Barcode.BarcodeName == barcode)

    instance.update({
        Barcode.GoodF: good_f,
        Barcode.Code: code,
        Barcode.Count: count,
        Barcode.Updated: 1.0,
        Barcode.Deleted: 0.0,
    })
    s.commit()
    s.close()

    del request.session['entered_barcode']
    del request.session['entered_code']
    del request.session['entered_count']
    del request.session['good_f']

    return HttpResponseRedirect(f'/scanok/goods/update/{pk}/')


class Store(ListView):
    template_name = 'stores.html'
    context_object_name = 'stores_list'

    def get_queryset(self):

app/scanok/templates/includes/footer.html
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="{% url 'index' %}" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="{% url 'accounts:devices' %}" class="nav-link px-2 text-muted">Devices</a>
        </li>
        <li class="nav-item"><a href="{% url 'scanok:goods' %}" class="nav-link px-2 text-muted">Goods</a></li>
        <li class="nav-item"><a href="{% url 'scanok:stores' %}" class="nav-link px-2 text-muted">Stores</a></li>
        <li class="nav-item"><a href="{% url 'scanok:users' %}" class="nav-link px-2 text-muted">Users</a></li>
        <li class="nav-item"><a href="{% url 'scanok:partners' %}" class="nav-link px-2 text-muted">Partners</a></li>
        <li class="nav-item"><a href="{% url 'scanok:dochead' %}" class="nav-link px-2 text-muted">DocHead</a></li>
    </ul>
    <p class="text-center text-muted">© 2022 Scanok</p>
</footer>

app/scanok/templates/includes/messages.html
{% if messages %}
        <div class="alert alert-danger" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
{% endif %}

app/scanok/templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:devices' %}">Devices</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'scanok:goods' %}">Goods</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'scanok:stores' %}">Stores</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'scanok:users' %}">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'scanok:partners' %}">Partners</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'scanok:dochead' %}">DocHead</a>
                </li>
            </ul>

            <span class="ml-auto">
            {% if request.user.is_authenticated %}
                <img src="{{ request.user.avatar_url }}" width="30" height="30" class="rounded-circle">

                <a href="{% url 'accounts:my-profile' %}" class="btn btn-outline-dark">My Profile</a>
                <a href="{% url 'logout' %}" class="btn btn-outline-dark">Logout</a>
            {% else %}
                <a href="{% url 'accounts:signup' %}" class="btn btn-outline-dark">Sign Up</a>
                <a href="{% url 'login' %}" class="btn btn-outline-dark">Login</a>
            {% endif %}
            </span>
        </div>
    </div>
</nav>

app/scanok/templates/includes/pagination.html
<nav aria-label="Page navigation example" id="Page_navigator">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{filter_param}}">&laquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link">&laquo;</a>
        </li>
        {% endif %}

        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="page-item active">
            <span class="page-link">{{ i }}</span>
        </li>
        {% else %}

        {% if i|add:"-3" <= page_obj.number and page_obj.number <= i|add:"3" %}
        <li class="page-item">
            <a class="page-link" href="?page={{ i }}&{{filter_param}}">{{ i }}</a>
        </li>


        {% elif i == page_obj.paginator.num_pages %}
        <li class="page-item">
            <span> ... </span>
        </li>
        <li class="page-item">

            <a class="page-link" href="?page={{ i }}&{{filter_param}}">{{ i }}</a></li>
        {% endif %}

        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{filter_param}}">&raquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link">&raquo;</a>
        </li>
        {% endif %}

    </ul>
</nav>

app/scanok/templates/includes/select_device.html
<p class="coin">
    <select aria-label="Default select example" name="" id="selectDevice" class="form-select" onchange="getval()">

    </select>
</p>